site_name: Agentic Docs
site_url: https://supercog.ai/agentic
theme:
  name: material
markdown_extensions: 
  - codehilite
  - toc
nav:
 - index.md  
 - building-agents.md
 - debugging.md
 - tools.md
 - rag.md
 - models.md
 - rest-api.md
 - cli.md
 - dashboard.md
 - project-structure.md
 - events.md
 - agentic-manifesto.md

