site_name: Agentic Docs
site_url: https://supercog.ai/agentic
theme:
  name: material
markdown_extensions: 
  - codehilite
  - toc
nav:
 - index.md  
 - Building_Agents.md
 - Debugging.md
 - Tools.md
 - Rag.md
 - Models.md
 - REST_API.md
 - CLI.md
 - Dashboard.md
 - PROJECT_STRUCTURE.md
 - EVENTS.md
 - AGENTIC_MANIFESTO.md

