site_name: Agentic Docs
site_url: https://supercog.ai/agentic
repo_url: https://github.com/supercog-ai/agentic
repo_name: supercog-ai/agentic
extra:
  version:
    provider: mike
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: default
    primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.follow
markdown_extensions: 
  - codehilite
  - toc
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
nav:
  - index.md
  - getting-started.md
  - Core Concepts:
    - Core Concepts: core-concepts/index.md
    - Agentic Design Principles: core-concepts/agentic-design-principles.md
    - Project Structure: core-concepts/project-structure.md
    - Event System: core-concepts/event-system.md
    - LLM Models: core-concepts/models.md
  - Building Agents:
    - Building Agents: building-agents/index.md
    - Debugging: building-agents/debugging.md
    - Agent Teams: building-agents/agent-teams.md
  - Interacting with Agents:
    - Interacting with Agents: interacting-with-agents/index.md
    - CLI: interacting-with-agents/cli.md
    - REST API: interacting-with-agents/rest-api.md
    - Next.js Dashboard: interacting-with-agents/nextjs-dashboard.md
    - Streamlit Dashboard: interacting-with-agents/streamlit-dashboard.md
  - Tools:
    - Tools: tools/index.md
    - Tool Library:
      - Tool Library: tools/tool-library/index.md
      - AirbnbCalendarTool: tools/tool-library/airbnb-calendar-tool.md
      - AuthorizedRestApiTool: tools/tool-library/authorized-rest-api-tool.md
      - BrowserUseTool: tools/tool-library/browser-use-tool.md
      - DatabaseTool: tools/tool-library/database-tool.md
      - DuckDuckGoSearchTool: tools/tool-library/duckduckgo-search-tool.md
      - FileDownloadTool: tools/tool-library/file-download-tool.md
      - GithubTool: tools/tool-library/github-tool.md
      - GoogleNewsTool: tools/tool-library/google-news-tool.md
      - HumanInterruptTool: tools/tool-library/human-interrupt-tool.md
      - IMAPTool: tools/tool-library/imap-tool.md
      - LinkedinDataTool: tools/tool-library/linkedin-data-tool.md
      - MCPTool: tools/tool-library/mcp-tool.md
      - MeetingBaasTool: tools/tool-library/meeting-baas-tool.md
      - OpenAIImageGenerator: tools/tool-library/image-generator-tool.md
      - PlaywrightTool: tools/tool-library/playwright-tool.md
      - RAGTool: tools/tool-library/rag-tool.md
      - RestApiTool: tools/tool-library/rest-api-tool.md
      - ScaleSerpBrowserTool: tools/tool-library/scaleserp-browser-tool.md
      - TavilySearchTool: tools/tool-library/tavily-search-tool.md
      - TextToSpeechTool: tools/tool-library/text-to-speech-tool.md
      - WeatherTool: tools/tool-library/weather-tool.md
  - rag-support.md
  - example-agents.md
