name: PR Summary Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - main
jobs:
  run-pr-agent:
    permissions: write-all
    name: run PR Summary Agent
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Download weaviate cache
        id: download-artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: pr-summary-agent.yml
          name: weaviate
          if_no_artifact_found: warn
          path: /home/runner/.cache/weaviate

      - name: Run agent
        run: |
          uv venv --python 3.12
          uv pip install -e "../${{ github.event.repository.name }}[all,dev]" --extra-index-url https://download.pytorch.org/whl/cpu --index-strategy unsafe-first-match
          uv pip install litellm[proxy]
          git diff --merge-base HEAD^1 HEAD > PRChanges.patch
          cat PRChanges.patch
          uv run pr_agent/PR_agent.py
    
        env: 
          OPENAI_API_KEY: ${{ secrets.PRAgentOpenAIKey }}
          PR_ID: ${{ github.event.pull_request.number }}
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
      
      - name: Update weaviate cache
        uses: actions/upload-artifact@v4
        with:
          name: weaviate
          path: /home/runner/.cache/weaviate
          overwrite: true
