name: Test PyPI Publish

on:
  workflow_dispatch:
    inputs:
      simulate_publish:
        description: 'Simulate the PyPI publish process'
        required: true
        type: boolean
        default: true

jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Verify authorized merger
        env:
          AUTHORIZED_USERS: ${{ secrets.AUTHORIZED_RELEASE_USERS }}
          CURRENT_USER: ${{ github.actor }}
        run: |
          echo "TESTING MODE: Checking if user $CURRENT_USER is authorized"
          if [[ ! ",$AUTHORIZED_USERS," == *",$CURRENT_USER,"* ]]; then
            echo "TEST RESULT: User $CURRENT_USER would NOT be authorized in production"
            echo "Continuing anyway since this is a test..."
          else
            echo "TEST RESULT: User $CURRENT_USER is authorized"
          fi
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          
      - name: Build package
        run: python -m build
        
      - name: Test PyPI publish
        if: github.event.inputs.simulate_publish
        run: |
          echo "TESTING MODE: This would publish to PyPI in production"
          echo "Running twine check to validate the package:"
          python -m twine check dist/*